print("Sammy's makes it fun in the sun.\n")
print("SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS")
print("SSSSSSSSSSSS Sammy’s makes it fun in the sun. SSSSSSSSSSSSSS")
print("SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS")